name: PluginEconomiaNeiZan
version: 1.0
main: com.neizan.plugin.Main
api-version: "1.19"

commands:
  balance:
    description: Muestra tu balance actual
    usage: /balance
  pay:
    description: Envía dinero a otro jugador
    usage: /pay <jugador> <cantidad>
  work:
    description: Selecciona un trabajo
    usage: /work
  jobstats:
    description: Muestra información de tu trabajo y balance
    usage: /jobstats
  jobs:
    description: Lista tus trabajos actuales
    usage: /jobs
  removejob:
    description: Quita un trabajo que tengas
    usage: /removejob <trabajo>
  jobinfo:
    description: Muestra información de cada trabajo
    usage: /jobinfo
